menu:
  主页: /
  归档: /archives

logo: 康兴华

more:
  友情链接: /links.html
  Github: https://github.com/kangxinghua/
  微博: http://weibo.com/kangxinghua
  知乎: https://www.zhihu.com/people/kangxinghua
  rss: /rss2.xml
  关于我: /

about:
  title: Theme Pln
  link: https://github.com/gaoryrt/hexo-theme-pln

disqus_shortname: mycommon

excerpt_num: 120

footer_info: © Simba 2015-2016